### ISSUE TITLE
Need to throw errors if everything is flagged

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#101]
Ruby experienced the error: 

% HISTOGRAM: Expression must be an array in this context: <LONG     (
              127)>.
% Execution halted at: VIS_CALIBRATE_SUBROUTINE  161
   /nfs/eor-00/h1/rbyrne/MWA/IDL_code/FHD/fhd_core/calibration/vis_calibrate_
  subroutine.pro
%                      VIS_CALIBRATE     164
   /nfs/eor-00/h1/rbyrne/MWA/IDL_code/FHD/fhd_core/calibration/vis_calibrate.
  pro
%                      FHD_MAIN          119

which arose from all of the tiles being flagged. This is a reminder to find a better, earlier place to error if all tiles or frequencies flagged.

**Comment by isullivan** [comment]
FHD should now exit with an error message before calibration if all tiles are flagged (as of commit 7df70f35)
