### ISSUE TITLE
Haslam simulation bug

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#109]
Simulated visibilities aren't created when the keyword galaxy_model is set (should simulate visibilities from the Haslam map).

Settings file:
[1061316296_settings.txt](https://github.com/EoRImaging/FHD/files/1601984/1061316296_settings.txt)

Error log:
[firstpass.e88712.1.txt](https://github.com/EoRImaging/FHD/files/1601986/firstpass.e88712.1.txt)

**Comment by nicholebarry** [comment]
Done.
