### ISSUE TITLE
References folder

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#136]
Ideas of things to add:
- The FHD paper
- Danny's pipeline paper
- Jack thesis with page numbers pointing to the Majick beam
- Adam's thesis, with page numbers to FHD-specific things
- My thesis, with page numbers
- Patti's thesis/paper for the catalog
- GLEAM paper for the catalog
- Sutinjo paper for the beam

Any others? Also should add a markdown page with descriptors to relevant items (posting an entire thesis with no guidance is not helpful)

**Comment by bhazelton** [comment]
Depending on the file size, theses may be too big to directly add to github. stable URLs might be better.
