### ISSUE TITLE
HERA calibration is unable to converge after recent updates pulled into master

### ISSUE THREAD

**Issue by jkerrigan** [EoRImaging/FHD#148]
When running HERA IDR2.1 data through the most recent updates in master the per frequency calibration never converges regardless of the allotted max iterations. I tracked this issue down to the specific commit that appears to be causing it and will attempt to narrow it down to the code level.

Commit: ff37abfa71fb581feb6e9c8015b7c2350d32f98d

**Comment by jkerrigan** [comment]
Issue appears to be confined to the reformulation(refactoring?) of the Jones matrix in fhd_struct_init_jones.pro.

**Comment by nicholebarry** [comment]
@dstorer Have you been able to calibrate HERA data recently? Do you think this is still an issue?

**Comment by dstorer** [comment]
I have been able to calibrate HERA data and haven't had trouble with it converging, so I think it's fair to say this issue is resolved.
