### ISSUE TITLE
Image filter "filter_uv_weighted" introduces a polarization bug

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#180]
The polarized output images created with the "filter_uv_weighted" seem to be combining polarization modes.

Here are the output Stokes I and Q images simulated from a polarized diffuse map and made with "filter_uv_uniform":
![stokesI_uniform](https://user-images.githubusercontent.com/12840057/70089286-a856e480-15cc-11ea-861b-81854b80f8f8.png)
![stokesQ_uniform](https://user-images.githubusercontent.com/12840057/70089304-b0af1f80-15cc-11ea-9a9b-488db7188bd6.png)

Here are the output Stokes I and Q images simulated from a polarized diffuse map and made with "filter_uv_weighted":
![stokesI_weighted](https://user-images.githubusercontent.com/12840057/70089379-cd4b5780-15cc-11ea-9e80-1ac1289cfcef.png)
![stokesQ_weighted](https://user-images.githubusercontent.com/12840057/70089396-d1777500-15cc-11ea-8e0e-375fc06ab5fc.png)

As you can see, the I and Q Stokes images are very similar when made with "filter_uv_weighted" and the Stokes Q power is way too high. Stokes U and V look fine.

**Comment by isullivan** [comment]
Could you also post the instrumental polarization images using `filter_uv_weighted`? It looks like YY is getting zeroed out, but it would be helpful to see more evidence.

**Comment by rlbyrne** [comment]
Here are the plotted .fits files from output_data. Something's weird with the YY flux scale:
XX:
![Model_weighted_XX](https://user-images.githubusercontent.com/12840057/70177074-84f46e00-168e-11ea-98cf-eddf2b628821.png)
YY:
![Model_weighted_YY](https://user-images.githubusercontent.com/12840057/70177084-89208b80-168e-11ea-945c-70f03c93e6ed.png)

**Comment by rlbyrne** [comment]
I found out that this issue was stemming from the renormalization factor, or filling factor, that is applied to images to account for partially-filled UV planes. The factor was calculated as an average across polarizations, which was suppressing YY power. When the factor was instead calculated per-polarization the issue disappears. (See PR #181)

Here are plots of Stokes I and Q after the correction. Stokes Q shows the features that we would expect from imaging with uniform weighting:
![stokesI](https://user-images.githubusercontent.com/12840057/70854722-db2a9380-1e7c-11ea-963a-476d6f48e71a.png)
![stokesQ](https://user-images.githubusercontent.com/12840057/70854723-dbc32a00-1e7c-11ea-83bf-71b97aa16745.png)

Here are plots of the instrumental polarization images. XX and YY are now on roughly the same flux scale:
![instXX](https://user-images.githubusercontent.com/12840057/70854730-fd241600-1e7c-11ea-9573-6403ae1b7a4d.png)
![instYY](https://user-images.githubusercontent.com/12840057/70854731-fd241600-1e7c-11ea-8441-53b903daec75.png)

**Comment by rlbyrne** [comment]
This issue is resolved by PR #181.
