### ISSUE TITLE
FILTER_NAME bug

### ISSUE THREAD

**Issue by lmberkhout** [EoRImaging/FHD#184]
get_image_renormalization.pro errors with the message below, and seems like it will always do so. It expects a variable "FILTER_NAME" to get passed in, but there is no keyword in the get_image_renormalization file for it so the keyword can never get passed in. I fixed this locally by allowing filter_name to be pulled from extra keywords in fhd_quickview and in get_image_renormalization.

Variable is undefined: FILTER_NAME.
% Execution halted at: GET_IMAGE_RENORMALIZATION   19
   /home/lmberkhout/data/MWA/FHD/fhd_output/get_image_renormalization.pro
%                      FHD_QUICKVIEW     280
   /home/lmberkhout/data/MWA/FHD/fhd_output/fhd_quickview.pro
%                      FHD_MAIN          250
   /home/lmberkhout/data/MWA/FHD/fhd_core/fhd_main.pro
%                      GENERAL_OBS       153
   /home/lmberkhout/data/MWA/FHD/Observations/general_obs.pro
%                      LMB_VERSIONS       87
   /home/lmberkhout/data/MWA/pipeline_scripts/FHD_IDL_wrappers/lmb_versions.p
  ro

**Comment by rlbyrne** [comment]
Ack this is my fault! I just pushed a fix. Please test it and then comment and close this issue if it worked.

As a side note, FHD loves to pass keywords through the "Extra" variable so it can be hard to know when they are and aren't defined.

**Comment by lmberkhout** [comment]
Seems to be fixed, thanks!
