### ISSUE TITLE
Rename keyword "max_sources" to "max_deconvolution_sources"

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#188]
The keyword "max_sources" refers to deconvolution only. I would be helpful if that keyword were renamed "max_deconvolution_sources" to avoid confusion.

**Comment by rlbyrne** [comment]
Since this actually refers to the number of deconvolution _components_, I actually think it would be better to rename the keyword "max_deconvolution_comps".

**Comment by isullivan** [comment]
You may as well just write the whole thing out then: `max_deconvolution_components`
