### ISSUE TITLE
Move documentation to a GitHub page

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#189]
Let's clean up FHD's documentation by developing a GitHub page with Jekyll where all the documentation can live.

**Comment by rlbyrne** [comment]
We need to figure out if Jekyll supports PDFs or Latex formatting. If not, we might need to find an alternative.

**Comment by nicholebarry** [comment]
Something tells me this never worked out, but I'm out of the loop here. @rlbyrne or @mwilensky768, care to elaborate?

**Comment by mwilensky768** [comment]
I think we just haven't gotten around to it.

**Comment by rlbyrne** [comment]
I think there's some question still about whether Jekyll will do what we want. There isn't a clear solution for how to do this with IDL. I also don't think this is a top priority for the repo.

**Comment by nicholebarry** [comment]
Since there isn't a clear solution, I'm going to close this issue.
