### ISSUE TITLE
Explain and Clean up vis_baseline_hist

### ISSUE THREAD

**Issue by mwilensky768** [EoRImaging/FHD#190]
The name `vis_baseline_hist` gets overloaded in several contexts and it is unclear what its function is.

There is a `vis_baseline_hist.pro` in `visibility_manipulation`, where `vis_baseline_hist` is then set within the procedure, presumably to some histogram object. It appears that `plot_cals.pro` uses an object named `vis_baseline_hist` and its attributes, however, in `vis_calibrate.pro`, `vis_baseline_hist` is treated as if it is a keyword, i.e. `IF Keyword_Set(vis_baseline_hist)...`. Finally, it is defaulted in `eor_wrapper_defaults.pro` in the `pipeline_scripts` repo, also as if it is a keyword.

**Comment by nicholebarry** [comment]
`vis_baseline_hist` histograms the calibrated visibilities or residual visibilities (depending on data products in your run), normalized to the model visibilities. It saves this as an output <obsid>_cal_hist.sav, and plots the histograms.

vis_baseline_hist is the keyword you set to enable this. It calls a function called vis_baseline_hist, which then sets a structure called vis_baseline_hist. A little confusing, but hey, very compact.

**Comment by nicholebarry** [comment]
updated
