### ISSUE TITLE
Beam setup error

### ISSUE THREAD

**Issue by aelanman** [EoRImaging/FHD#204]
Recent changes seem to be causing some problems in the MWA beam setup. I'm not entirely up to date on what these changes do, but when I run FHD with MWA beams it fails on this line:

https://github.com/EoRImaging/FHD/blob/797d9fc2219e8188a7c1c872e0bd16c229aee8ae/fhd_core/beam_modeling/beam_power.pro#L34

The variable `di_uv_use` is not defined in this procedure, nor can I see where it gets calculated. It loks like this was changed last November, on commit bd90cac50.

**Comment by rlbyrne** [comment]
Oh no I can't believe I didn't catch that! Fixing it right now.

For the record, this bug was introduced by PR #203
