### ISSUE TITLE
output_images don't get made 

### ISSUE THREAD

**Issue by dseitova** [EoRImaging/FHD#222]
output_images folder is empty, while there are files in output_data folder when 
calibrate_visibilities=0 and model_visibilities=0.
(also rerun it with export_images=1)

**Comment by rlbyrne** [comment]
I just reran this job and _did_ get .png outputs. I wonder if this is an environment issue rather than an FHD issue.

**Comment by nicholebarry** [comment]
@dseitova @rlbyrne Did this get resolved? Was it an environment issue as expected?

**Comment by rlbyrne** [comment]
I think we concluded that this was an environment issue. I'm going to close this issue for now. @dseitova, let me know if I'm off-base with this and we will reopen.
