### ISSUE TITLE
Minimum baseline calculation in obs init vs degridding/gridding

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#242]
In calculating the minimum baseline length in wavelengths, we use the u and v speed of light travel time and the frequency of the measurement. We also cast the calculation of the baseline length array into a Float (probably because the precision isn't needed and it's a very large array, but I could be wrong).

However, * where * the casting happens in the calculation is different for gridding/degridding and the initialisation of the obs structure, so the answers are slightly different. For the MWA, the minimum baseline length in lambda is calculated to be 4.30430 in the obs structure initialisation and 4.3042951 in gridding/degridding. This is a problem because the obs.minimum_baseline is used in logic in gridding/degridding to flag individual visibilities which are below the threshold.

This small discrepancy results in different flagging between even and odd eppsilon inputs.

**Comment by isullivan** [comment]
Good catch! We should make the calculation for the value in the obs structure match what is used for gridding.

**Comment by nicholebarry** [comment]
Okay, will do. I may also try to see where full precision would be worthwhile (for example, if double_precision keyword is set)

**Comment by isullivan** [comment]
Sorry, one more comment: While I think the calculation in the obs structure should match what's used in gridding/degridding, those should then just use the value stored in the obs structure so that we are guaranteed to use the same value everywhere.
