### ISSUE TITLE
Possible bug in crosspol phase calculation

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#260]
I believe the calculation in `vis_calibration_crosspol_phase` is incorrect. Here's a writeup of what I think the corrected math would be:

[Potential_Crosspol_Phase_Calculation_Error.pdf](https://github.com/EoRImaging/FHD/files/6475202/Potential_Crosspol_Phase_Calculation_Error.pdf)

Testing is needed to see if this is a real bug and to determine how large of an effect it is.

**Comment by isullivan** [comment]
Interesting, this is a different result than in: https://github.com/EoRImaging/FHD/blob/master/fhd_core/calibration/crosspol_phase_calculation_memo.pdf
Could you check that memo for errors, and if it is incorrect we should change the code and that memo.

**Comment by rlbyrne** [comment]
Unfortunately the calculation in that memo only deals with visibilities are reported with the "PQ" polarization convention. The actual implementation in the code tries to account for the fact that, in practice, we work with visibilities with both "PQ" and "QP" polarizations. There should be a sign flip when the visibilities are conjugated into the "QP" polarization convention.

**Comment by rlbyrne** [comment]
Pyxie found a sign error in the new memo, but the main issue is the sign difference between the two terms in the numerator and that persists with the correction. Here is the updated memo (also with the math in more gory detail, and fixing a typo where I didn't include the summation in the result.)

[Potential_Crosspol_Phase_Calculation_Error.pdf](https://github.com/EoRImaging/FHD/files/6475645/Potential_Crosspol_Phase_Calculation_Error.pdf)
