### ISSUE TITLE
Bug with new calibration routine

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#262]
I'm rerunning the diffuse survey, and 121 of 178 observations that processed successfully in the past failed in calibration with the following message:

% REBIN: Expression must be an array in this context: XVALS.
% Execution halted at: EXTRACT_SUBARRAY    7
   /home/ubuntu/MWA/FHD/fhd_utils/IDL_tools/extract_subarray.pro
%                      VIS_CALIBRATION_FLAG   29
   /home/ubuntu/MWA/FHD/fhd_core/calibration/vis_calibration_flag.pro
%                      VIS_CALIBRATE     209
   /home/ubuntu/MWA/FHD/fhd_core/calibration/vis_calibrate.pro
%                      FHD_MAIN          135
   /home/ubuntu/MWA/FHD/fhd_core/fhd_main.pro
%                      GENERAL_OBS       146
   /home/ubuntu/MWA/FHD/Observations/general_obs.pro

I'm attaching the settings file of one of the failed observations:
[1130773144_settings.txt](https://github.com/EoRImaging/FHD/files/6530176/1130773144_settings.txt)

**Comment by isullivan** [comment]
This looks like it is happening because all of the frequencies have been flagged. From the settings file only 48 are flagged going into this, so they must be being cut at line 48 or 71 of `vis_calibration_flag.pro`. I can't be sure which part is failing, though.

When you ran the diffuse survey before, are you sure you had `flag_calibration` set? It defaults to 1, but I thought we had turned it off for some runs.

**Comment by rlbyrne** [comment]
No, I haven't set `flag_calibration` explicitly in any runs.

**Comment by rlbyrne** [comment]
Here's more information about what I've tried:

I reverted the code to 2f79c44 and reran. I then ran into the bug documented in Issue #243, so I checked out the latest version of source_dft_multi and was otherwise running the 2f79c44 code version. I encountered the exact same bug as above.

Next I tried setting `flag_calibration=0` and rerunning. This time I hit a different bug:
% Array dimensions must be greater than 0.
% Execution halted at: FHD_SOURCE_DETECT   66
   /home/ubuntu/MWA/FHD/fhd_core/deconvolution/source_detection/fhd_source_de
  tect.pro
%                      FAST_HOLOGRAPHIC_DECONVOLUTION  312
   /home/ubuntu/MWA/FHD/fhd_core/deconvolution/fast_holographic_deconvolution
  .pro

The output log lists `Initial convergence:-NaN`, which looks suspicious. I thought this might be yet another old bug that had since been fixed, so I went back to the latest version and reran. I got the same error. Next I went even further back in code history, to f16613c (once again checking out the latest source_dft_multi), and reran. I got the same error.

The keywords I'm setting are:
      recalculate_all = 1
      flag_calibration = 0
      uvfits_version = 5
      uvfits_subversion = 1
      max_deconvolution_components = 200000
      calibration_catalog_file_path = filepath('GLEAM_v2_plus_rlb2019',root=rootdir('FHD'),subdir='catalog_data')
      max_cal_iter = 1000L ;increase max calibration iterations to ensure convergence
      gain_factor = 0.1
      deconvolve = 1
      return_decon_visibilities = 1
      deconvolution_filter = 'filter_uv_uniform'
      filter_background = 1
      return_cal_visibilities = 1
      diffuse_calibrate = 0
      diffuse_model = 0
      cal_bp_transfer = 0
      rephase_weights = 0
      restrict_hpx_inds = 0
      hpx_radius = 15
      subtract_sidelobe_catalog = filepath('GLEAM_v2_plus_rlb2019',root=rootdir('FHD'),subdir='catalog_data')
      return_sidelobe_catalog = 1
      dft_threshold = 0
      ring_radius = 0
      write_healpix_fits = 1
      debug_region_grow = 0
      n_pol = 4
      time_cut = -4
      snapshot_healpix_export = 0

The affected observations are:
1130773024
1130773144
1130774824
1130774944
1130776624
1130776624
1130776744
1130778424
1130778544
1130780224
1130780344
1130782024
1130782144
1130783824
1130783944
1130785624
1130785744
1130787544
1130787664
1130789344
1130789464
1131455976
1131457776
1131459576
1131461376
1131463296
1131465096
1131466896
1131468696
1131470496
1131472296
1131474096
1131536384
1131536624
1131709912
1131713512
1131722632
1131724432
1131731632
1131733432
1131735232
1131740752

**Comment by nicholebarry** [comment]
It seems as though there's like 4 sources with nan fluxes in the specified catalog. I don't why that would suddenly appear, but they might be covering the model uv plane with nans and thereby gutting the calibration.

I've made a simple fix to exclude nan fluxes and print a warning. Please pull the branch nan_flux_hotfix and check to see if this fixes your issue.

**Comment by rlbyrne** [comment]
I just tested nan_flux_hotfix and ran into this error:
% Variable is undefined: SOURCE.
% Execution halted at: GENERATE_SOURCE_CAL_LIST  156
   /home/ubuntu/MWA/FHD/fhd_core/calibration/generate_source_cal_list.pro
%                      FHD_MAIN          103
   /home/ubuntu/MWA/FHD/fhd_core/fhd_main.pro

**Comment by rlbyrne** [comment]
I removed all sources with nan flux from the GLEAM catalog and reran (I have no idea why those sources existed, that could be something to look into). Most of the observations processed successfully, but I got the exact same error for five observations:
1131465096
1131466896
1131468696
1131470496
1131474096

**Comment by rlbyrne** [comment]
Closed by #264.

This is mostly resolved by PR #263, but let's wait on closing the issue until #264 is tested and merged.
