### ISSUE TITLE
Bug in beam_image

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#278]
I'm encountering a new bug in `beam_image.pro` on the master branch. This is the full traceback:
model_res=model_res*group_n[gi_use[gi]]
                                                         ^
% Syntax error.
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 98

        ENDIF ELSE BEGIN
         ^
% Type of end does not match statement (ENDFOR expected).
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 102

        ENDIF ELSE BEGIN
               ^
% Syntax error.
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 102

        ENDELSE
               ^
% Type of end does not match statement (ENDIF expected).
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 114

                  model_res=model_res*group_n[gi_use[gi]]
                                                         ^
% Syntax error.
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 144

        ENDIF ELSE BEGIN
         ^
% Type of end does not match statement (ENDFOR expected).
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 146

        ENDIF ELSE BEGIN
               ^
% Syntax error.
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 146

        ENDELSE
               ^
% Type of end does not match statement (ENDIF expected).
  At: /home/rbyrne/FHD/fhd_core/beam_modeling/beam_image.pro, Line 151
% Attempt to call undefined function: 'BEAM_IMAGE'.
% Execution halted at: GENERATE_SOURCE_CAL_LIST   40

**Comment by isullivan** [comment]
The bug is that line 98 is missing a closing parenthesis. This was introduced in commit 941d3c5 of PR #269

**Comment by rlbyrne** [comment]
Testing that fix now! Thanks.

**Comment by rlbyrne** [comment]
Closed by #277
