### ISSUE TITLE
Floor in calibration simulations with perfect calibration, part 2

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#41]
Things were getting out of hand. This issue is the continuation of Issue #39.

Here are the interpolation results given various psf resolutions. The previous post on Issue #39 did not actually interpolate, but somehow encompasses a change that affected the window during the comparison of the default and the default with attempted interpolation. What caused that is unknown.

In any case, here is the updated interpolation tests. The difference 2D PS plots are the default resolution of 100 without interpolation minus interpolation with psf resolutions of: 8,16,32,100,500.
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_jan_obs_id_6176_minus_psf8interpol_10source_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12940055/493cc556-cf7a-11e5-9914-de29fb50d718.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_jan_obs_id_6176_minus_psf16interpol_10source_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12940060/4cb485de-cf7a-11e5-9f0b-bebd14db0d12.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_jan_obs_id_6176_minus_psf32interpol_10source_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12940061/4fd20746-cf7a-11e5-9bd0-371b961b219b.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_jan_obs_id_6176_minus_psf100interpol_10source_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12940064/530353e8-cf7a-11e5-8737-bb93940a61ed.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_jan_obs_id_6176_minus_psf500interpol_10source_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/12940066/561230c2-cf7a-11e5-90af-71960cb1068c.png)

I think the 1D PS plots are more indicative of what is happening. The ordering is interpolation with psf resolutions of 8,16,32,100,500.

![fhd_nb_sim_perfect_psf8interpol_10source_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/12940088/7b103d92-cf7a-11e5-8ce0-8094a4da2f0d.png)
![fhd_nb_sim_perfect_psf16interpol_10source_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/12940090/7ff688c0-cf7a-11e5-8f1a-fb6684837815.png)
![fhd_nb_sim_perfect_psf32interpol_10source_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/12940093/862c88c0-cf7a-11e5-9d8a-fc85fd31328c.png)
![fhd_nb_sim_perfect_psf100interpol_10source_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/12940100/9083cdce-cf7a-11e5-8c56-0516f59d8577.png)
![fhd_nb_sim_perfect_psf500interpol_10source_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/12940101/9354ea74-cf7a-11e5-8c80-a08dff5d868f.png)

Interpolation has successfully reduced "bumps" at high k which indicated psf resolutions that were too coarse, even at the default psf resolution of 100. However, there appears to be an uncaptured normalization that depends on the psf resolution. This actually makes the psf resolution of 8 better! This also indicates why the psf resolution of 500 had such a negatived huge difference in the 2D PS.

Thoughts on what is causing this is appreciated. I feel like we might be getting somewhere with this EoR window floor problem.

Timing and mem usage...(with a 10 source input and modeling/subtracting 5)
psf res 100, no interpolation: 23.6G, 1:32
psf res 8, interpolation: 21.3G, 2:19
psf res 16, interpolation: 22.3G, 2:19
psf res 32, interpolation: 22.4G, 2:18
psf res 100, interpolation: 21.3G, 2:19
psf res 500, interpolation: 24.3G, 3:30

**Comment by bhazelton** [comment]
This is fascinating, Nichole. I agree with your reasoning, and I think once
we run down the normalization issue we're going to be very happy with the
interpolation.

**Comment by nicholebarry** [comment]
Ian changed the calculation of the beam integral from float to double precision. We suspect that this could be the cause of the normalization error.

Below are 2D difference plots from default (psf resolution of 100, no interpolation) and the tests (interpolation, double precision during normalization, and psf resolutions of 8,16,32,100). Color bars are not constrained, but I think you get the idea anyway.

![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_2_obs_id_6176_minus_psf8interpol_10source_dnorm_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/13015238/ddb895fe-d16c-11e5-9922-c9d0f3773c76.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_2_obs_id_6176_minus_psf16interpol_10source_dnorm_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/13015244/e8bfb6c6-d16c-11e5-9459-3a5063b7cee4.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_2_obs_id_6176_minus_psf32interpol_10source_dnorm_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/13015247/ec95f1b6-d16c-11e5-815a-0d009a08b5b1.png)
![fhd_nb_sim_perfect__cal_noeor_ones_maxcalsources_nod_zenithpointing_notileflag_5outof10_2_obs_id_6176_minus_psf100interpol_10source_dnorm_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/13015253/f18c4ac6-d16c-11e5-938d-9862805e4859.png)

Here are the 1Ds for the tests (interpolation, double precision, and psf resolutions of 8,32,100). I didn't let a couple of tests run long enough, but again, I think you got the idea.

![fhd_nb_sim_perfect_psf8interpol_10source_dnorm_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/13015278/0aa66334-d16d-11e5-85f8-f823b9bf92e6.png)
![fhd_nb_sim_perfect_psf32interpol_10source_dnorm_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/13015289/172868e6-d16d-11e5-92fa-fc90922e313e.png)
![fhd_nb_sim_perfect_psf100interpol_10source_dnorm_obs_id_6176_bh_1dkpower](https://cloud.githubusercontent.com/assets/5588290/13015295/1db18878-d16d-11e5-9787-e9d1c781951c.png)

It seems as though switching to double precision did make it so the tests were more similar. However, their is still a significant floor.

We store the beam integral during firstpass, so we can make sure that the beam integral calculation is similar between the runs. And they are, in fact, much more similar than before.

psf 8 -- 0.0633313
psf 16 -- 0.0633364
psf 32 -- 0.0633385
psf 100 -- 0.0633386

For float precision, the beam integrals were...

psf 8 -- 0.0633082
psf 16 -- 0.0633141
psf 32-- 0.0633164
psf 100 -- 0.0633106

It seems as though the beam integral is systematically *higher* for double precision. I wouldn't have expected this...

**Comment by bhazelton** [comment]
Do we have any idea why the dirty (really the full model) and residual (the
model of the faint stuff) are all red while the model (the model of the
bright stuff) is mixed with light blue in the window? These look nothing
like the earlier differences, I'm really not sure how to interpret them.

**Comment by isullivan** [comment]
The 1D plots look really good, with no noise floor and staying very smooth at high k. I assume we should not expect the model line to actually touch the EoR line? Is that a separate test? Also, for the 2D plots, did you start completely fresh and use the new code to first make the dirty visibilities? I'm confused by the solid bright red throughout the dirty and residual, just like Bryna. This should have been a fairly subtle change, so I'm concerned that this is catching something else, as well. Also, these changes in the beam integral normalization should affect the model in exactly the same way. So, it really looks like there might be some other difference at the point of generating the input dirty visibilities. Have a look at their settings and grid_out.o files, and then also post them or send them to me if there isn't an obvious cause.

**Comment by nicholebarry** [comment]
I found the error. The input visibilities contained over 6000 sources, and the model only subtracted the brightest 5 sources. I effectively just mixed my two simulations together in a bad way. I'll rerun them.

During telecon, people suggested that the beam integral could be systematically higher for double precision because of truncation for float precision.

**Comment by isullivan** [comment]
May be related to #66

**Comment by nicholebarry** [comment]
Closed. See upcoming limit paper / everything I've done for the past two years.
