### ISSUE TITLE
Persist antenna tables from uvfits files

### ISSUE THREAD

**Issue by isullivan** [EoRImaging/FHD#45]
Uvfits files contain an antenna table with positions of every antenna. That information needs to be captured in FHD so that proper uvfits files can be written.

**Comment by bhazelton** [comment]
How hard is this @isullivan? We're starting to bump up against this for simulation work where students want to take FHD simulations into PAPER style analyses.

**Comment by isullivan** [comment]
I think it's not *too* hard, maybe a half day of work and then some testing. I can fit it in over the next few weeks, or sooner if it's blocking someone right now.

**Comment by bhazelton** [comment]
Thanks. I don't think it's super urgent, but it is starting to be a problem.

**Comment by bhazelton** [comment]
There is an antenna structure, it's not typically persistent, that should change.

**Comment by bhazelton** [comment]
Done in PR #77.
