### ISSUE TITLE
Diffuse map normalization

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#46]
There appears to be a normalization change in the diffuse maps depending on the pixel resolution specified. I've specified a dimension of 2048 and 4096.

For the zenith pointing of a deconvolution run with 2048:
![eor0_diffuse_march2016_small_zenith](https://cloud.githubusercontent.com/assets/5588290/14396601/5e817a2e-fd8d-11e5-9c11-c26873a5f9db.png)

For the zenith pointing of a deconvolution run with 4096:
![eor0_diffuse_march2016_zenith](https://cloud.githubusercontent.com/assets/5588290/14396612/6a674c7e-fd8d-11e5-94fb-10426daa0697.png)

I have many more examples of this as well if anyone wants them.

Here is a histogram I made of the pixel values for each map to highlight the distribution of the values.
![diffuse_pixel_histogram_i](https://cloud.githubusercontent.com/assets/5588290/14396634/936444c4-fd8d-11e5-93b0-ffb0c405ab97.png)

I have also made it for Stokes Q, which also experiences a similar difference.
![diffuse_pixel_histogram_q](https://cloud.githubusercontent.com/assets/5588290/14396651/a593b8d2-fd8d-11e5-884e-ff84d6e2c046.png)

**Comment by nicholebarry** [comment]
Updates: 

1. I noticed that some functions (dirty_image_generate and get_image_renormalization) were passing degpix, which was not specified in combine_obs_healipix. I passed obs.degpix instead, and only got very minor (floating point) differences in the final diffuse maps.

2. I tried forcing get_image_renormalization to be the same for both dimensions. I got different (and wrong, obviously) answers.

3. I regenerated the maps at the Healpix nside that corresponded to their dimension (2048 with a nside of 2048, 4096 with a nside of 4096) to see if it was a Healpix-specific issue. Got the same results as before.

4. I specified a baseline_threshold. This was on my to-do list anyways in order to try to diminish the small-scale structure dependence. I tried a baseline_threshold of 100 wavelengths, and got bad bad things. The normalization is all wrong (magnitudes of ~10^6 instead of 0.5), and the large-scale structure went away.

**Comment by nicholebarry** [comment]
Ian found some things that might help with the normalization. With those fixes, I reran the 2048 and 4096 zenith pointing decon runs. 

The problem still persists.

dimension of 2048
![eor0_diffuse_march2016_small_normfix](https://cloud.githubusercontent.com/assets/5588290/14474085/106f8198-00b0-11e6-92a3-4a8f3ddd4684.png)

dimension of 4096
![eor0_diffuse_march2016_normfix](https://cloud.githubusercontent.com/assets/5588290/14474097/20ea8ebe-00b0-11e6-8ebf-0f81450b7407.png)

**Comment by nicholebarry** [comment]
Ian applied a correction factor based off of the pixel area / healpix pixel area, and applied it only to the data. The hope is that the two maps (made from the 2048 dimension and 3072 dimension deconvolutions) will have the same normalization, even if it is off by a few orders of magnitude.

Here are the results:

3072 deconvolution (smaller pixel resolution)
![eor0_diffuse_march2016_normfix_414](https://cloud.githubusercontent.com/assets/5588290/14555375/10b6e3f0-02a7-11e6-8668-918fd8b2d5e5.png)

2048 deconvolution (original pixel resolution)
![eor0_diffuse_march2016_small_normfix_414](https://cloud.githubusercontent.com/assets/5588290/14555388/2a03663a-02a7-11e6-9cca-9893188f3cb8.png)

I was also able to match the healpix pixels between the two runs and subtract the maps at those pixels. Here is 3072 deconvolution minus 2048 deconvolution.

**Comment by isullivan** [comment]
That looks pretty good! We should check that these new maps work as input for diffuse subtraction and calibration, but then I think we can mark this as closed.

**Comment by bhazelton** [comment]
Looks great! Good sleuthing!

**Comment by nicholebarry** [comment]
I inputed this new diffuse map into FHD for calibration, and most observations failed to calibrate. Those that did, look very weird. Barring any coincidental errors, perhaps the diffuse maps need tweaking. I'm still working on getting a diffuse map to compare to with the RTS.

**Comment by isullivan** [comment]
I just started a few tests of my own, to see what's going on and try to debug this. I should hopefully be able to get back to you in a few days.

**Comment by nicholebarry** [comment]
Here are the tests and results that we talked about.

I created 4 maps, varying dimension and nside.

Dimension=2048, nside=4096
![eor0_diffuse_2048_4096](https://cloud.githubusercontent.com/assets/5588290/14652521/87c945e8-0629-11e6-8fdc-9ccd2494c76c.png)

Dimension=2048, nside=2048
![eor0_diffuse_2048_2048](https://cloud.githubusercontent.com/assets/5588290/14652532/93adbb96-0629-11e6-87da-85527632524b.png)

Dimension=1024, nside=4096
![eor0_diffuse_1024_4096](https://cloud.githubusercontent.com/assets/5588290/14652545/a056afa6-0629-11e6-8da1-49eb9db968bf.png)

Dimension=1024, nside=2048
![eor0_diffuse_1024_2048](https://cloud.githubusercontent.com/assets/5588290/14652563/b08d59d8-0629-11e6-8334-35674c8851c9.png)

I also created histograms of their pixel values.
![pixel_distribution_nsidemaps](https://cloud.githubusercontent.com/assets/5588290/14652581/c621c8e2-0629-11e6-9b6f-dba3d7441948.png)

**Comment by nicholebarry** [comment]
Ian and Bryna suggested I look at the uv plane with these different uv extents to see if there is a significant difference. This is to make sure that all of our pixel conversions and whatnot are not completely fruitless.

I made residual gridded uv cubes for both the 1024x1024 and 2048x2048 extents from the runs in the previous comments. I then either divided them by their corresponding visibility count per pixel (to make it uniform weighted, if I can say that in this frame)  or their corresponding weights (to make it in the apparent frame, again if that is something I can say. Really, someone tell me how I should describe these things).

I then selected the inner 1024x1024 amplitude from the 2048x2048 extent and differenced that from the 1024x1024 original amplitude. I'll plot the results below, along with the 1024x1024 original for easy unit comparisons.

If I've done this right, I think there is a large enough difference for a little bit of concern. "small - large" refers to the order in which I've taken the difference (1024x1024 minus inner 2048x2048)

![uniform_res](https://cloud.githubusercontent.com/assets/5588290/15386737/5186be6a-1d5e-11e6-9ada-d4e26a74e7d1.png)

![uniform_res_diff](https://cloud.githubusercontent.com/assets/5588290/15386740/5660677e-1d5e-11e6-8d40-36fffa471ce4.png)

![apparent_res](https://cloud.githubusercontent.com/assets/5588290/15386743/5ba60e96-1d5e-11e6-80b7-882b7ff62db1.png)

![apparent_res_diff](https://cloud.githubusercontent.com/assets/5588290/15386750/6038d60a-1d5e-11e6-8fb0-e00f82733f30.png)

**Comment by adampbeardsley** [comment]
Interesting.
In the "uniform" case, it looks like "large" has values pretty much a factor of two smaller than "small". One could argue this is expected depending on the FT convention - if there's a 1/Npix in there, the larger values might be trying to account for that (nevermind the fact that Npix is actually 4x larger, not 2x). But that scaling only works if you're actually sampling the entire gridded plane. What does the uv extent actually look like? In other words, does the larger extent contain baselines that were not included in the smaller extent version?
The "apparent" case looks encouraging. But the streaks are still odd. It's probably places where you're dividing by very small weights factors, but they really should be identical.
Just my thoughts.

**Comment by nicholebarry** [comment]
The larger uv extent does include baselines not included in the smaller extent version. 

If I were to constrain the baselines, the uv plane should be 0 everywhere after the specified point, but the number of pixels will still be the same. I can definitely test it, but my hunch is that the uniform normalization will not change because the same number of pixels are still being used, even if a bunch are 0.

I think you're right about the weights.

**Comment by nicholebarry** [comment]
Alright, same thing as above, but using the point source simulations that have a hard 512 wavelength cut for both (which were created for different reasons, but used here to bug hunt).

See previous comment for explanation.

![uniform_res_512 png](https://cloud.githubusercontent.com/assets/5588290/15488386/a4d3aa10-210a-11e6-8bb8-7c8d663aad6d.png)

![uniform_res_diff_512 png](https://cloud.githubusercontent.com/assets/5588290/15488388/ab23e902-210a-11e6-93c1-be7db204003e.png)

![apparent_res_512 png](https://cloud.githubusercontent.com/assets/5588290/15488389/afa95a66-210a-11e6-94c1-1edd48eddab5.png)

![apparent_res_diff_512 png](https://cloud.githubusercontent.com/assets/5588290/15488392/b4af9548-210a-11e6-8d71-ea5101834f56.png)

The non-difference images shown above have aliasing effects (I think) from the cut. They actually look pretty bad...

**Comment by isullivan** [comment]
Could you change the color stretch of the difference images? Also, what do you mean by aliasing effects? I would expect FFT'd images of these to have very noticeable ringing from the hard circular cut, but that is nothing to be worried about. Do you see an aliasing effect in the UV plane? From what I can see here so far, this looks fairly encouraging, and leads me to suspect that the mis-subtraction you were seeing with the five point source test comes from calculating the primary beam correction with beam_image. 
To confirm that, you could call dirty_image_generate on the two uv planes you show here (small uncropped and large cropped), and look at the raw difference. If you supply an obs structure to dirty_image_generate, make sure it's from the small uncropped version for both or the normalization will be off.

**Comment by nicholebarry** [comment]
I see something reminiscent of a aliasing effect in the UV plane, whether it is aliasing is up for debate. There are really *two* things that both me about the uniform and apparent UV residual in the previous comment: there is a "pinching" effect along the V axis along U=0 (where U=0 should be, not where it is indicated on the plots, whoops) that almost looks like those "unfocus your eyes and see a dinosaur/heart/cat" diagram, and there is a striation effect along the V axis for all U (zoom into one of those images, and you'll see about every other pixel dip back down to 0).

The five point source test was for a different issue a long time ago; the data from the previous comments is real data. We did come to the conclusion that test had differences on the order of float/double in the residuals, but that was testing if subtraction was being performed correctly.

I am running a max_baseline = 512 wavelengths for the real data tests. I want to make sure that diffuse is being normalized correctly, so I want to test things out with diffuse data.

Here is the zoomed in apparent and uniform differences between extents from above.
![apparent_res_diff_512_sim_zoom](https://cloud.githubusercontent.com/assets/5588290/15510693/61489b06-218d-11e6-961a-390faf0dbf89.png)
![uniform_res_diff_512_sim_zoom](https://cloud.githubusercontent.com/assets/5588290/15510700/665de5ce-218d-11e6-8812-52c3f8b16e64.png)

**Comment by nicholebarry** [comment]
Images that Miguel suggested: real, imaginary, and phase difference of the point source simulations

![apparent_res_diff_512_sim_zoom2](https://cloud.githubusercontent.com/assets/5588290/15518035/c65f788a-21af-11e6-83e9-e1fa550bda4a.png)
![uniform_res_diff_512_sim_zoom2](https://cloud.githubusercontent.com/assets/5588290/15517980/75890f16-21af-11e6-8bfb-560e0f91eeae.png)
![apparent_res_diff_512_sim_zoom2_imag](https://cloud.githubusercontent.com/assets/5588290/15518004/9541b9f2-21af-11e6-89e8-b318821fcc59.png)
![uniform_res_diff_512_sim_zoom2_imag](https://cloud.githubusercontent.com/assets/5588290/15518011/9abb4c7c-21af-11e6-8d77-e1f0638c59a6.png)
![apparent_res_diff_512_sim_zoom2_phase](https://cloud.githubusercontent.com/assets/5588290/15518015/9f2914ce-21af-11e6-8959-a64fed1b59ca.png)
![uniform_res_diff_512_sim_zoom2_phase](https://cloud.githubusercontent.com/assets/5588290/15518017/a3584ccc-21af-11e6-8934-cb4a3afe7c53.png)

**Comment by nicholebarry** [comment]
More plots requested

Weights
![weights_diff_512_sim_zoom2_abs](https://cloud.githubusercontent.com/assets/5588290/15523072/64c5416e-21cc-11e6-950a-1ea1f6960bad.png)
![weights_diff_512_sim_zoom2_imag](https://cloud.githubusercontent.com/assets/5588290/15523075/64cb3146-21cc-11e6-84b5-31999f2ffb20.png)
![weights_diff_512_sim_zoom2_phase](https://cloud.githubusercontent.com/assets/5588290/15523073/64c63ce0-21cc-11e6-96a4-0265a592c286.png)
![weights_diff_512_sim_zoom2_real](https://cloud.githubusercontent.com/assets/5588290/15523074/64ca3e3a-21cc-11e6-8608-1e9bea3b1626.png)

Vis count
![vis_count_diff_512_sim_zoom2_abs](https://cloud.githubusercontent.com/assets/5588290/15523082/7784c1f8-21cc-11e6-85fb-72bc0c5f3f97.png)
![vis_count_diff_512_sim_zoom2_imag](https://cloud.githubusercontent.com/assets/5588290/15523085/778b725a-21cc-11e6-82c0-9ae8dde0018b.png)
![vis_count_diff_512_sim_zoom2_phase](https://cloud.githubusercontent.com/assets/5588290/15523083/77871b38-21cc-11e6-9682-c84060ab52b6.png)
![vis_count_diff_512_sim_zoom2_real](https://cloud.githubusercontent.com/assets/5588290/15523084/77881bf0-21cc-11e6-9e3e-94d14b10fbe6.png)

Slices (over smaller ranges in U to look at the part of the UV plane that has the least 0 points)
![apparent_v_slice](https://cloud.githubusercontent.com/assets/5588290/15523061/4acc7fca-21cc-11e6-8dd5-47ed9ff51e3c.png)
![apparent_diff_v_slice](https://cloud.githubusercontent.com/assets/5588290/15523063/4ffbaeda-21cc-11e6-82dd-813fb9193966.png)

**Comment by nicholebarry** [comment]
More plots requested

A slice in V for the phase of a point source simulation. Lots of wrapping!
![apparent_v_slice_sim_phase](https://cloud.githubusercontent.com/assets/5588290/15526056/d57adc2c-21e3-11e6-8308-46202b189d10.png)

And now for a different run. I have REAL data with diffuse in it, but now with the same max baseline!
I ran a couple of plots. I can make more given requests, since making all of the requested plots for this run would amount to ~10 plots.
![data_apparent_res_diff_512_abs](https://cloud.githubusercontent.com/assets/5588290/15526093/29617b7a-21e4-11e6-9bf2-ae04225ede41.png)
![apparent_res_512_data](https://cloud.githubusercontent.com/assets/5588290/15526098/346bab4e-21e4-11e6-8add-43fcd058878b.png)
![data_apparent_res_diff_512_phase](https://cloud.githubusercontent.com/assets/5588290/15526113/3a3b59fc-21e4-11e6-8fa4-c3409ca06909.png)
![apparent_res_512_phase_data](https://cloud.githubusercontent.com/assets/5588290/15526115/3ec88936-21e4-11e6-8295-cff1a0eed73e.png)

Ian, I can do you weights / vis count plots tomorrow

**Comment by nicholebarry** [comment]
A while ago, it was suggested the diffuse normalization between different UV extents might be caused by the beam calculation. The beam calculation resolution is dependent on the UV extent. 

To test this, I transferred over the psf structure (which contains beam info) from a run with a normal UV extent (2048) to one with a large UV extent (3072) so that their beams would be the same. I then histrogrammed the resulting diffuse maps like I've done before.

In comparing the distributions, it appears that there is essentially no difference between a large UV extent run (dim 3072, psf 3072) and a large UV extent run with a regular beam (dim 3072, psf 2048).

![pixel_distribution_psftransfer](https://cloud.githubusercontent.com/assets/5588290/16821438/1fb16c40-490b-11e6-9dda-79ae4d672858.png)

**Comment by nicholebarry** [comment]
This is where we left this discussion last time. I ran some tests with constraining the maximum baseline used and made diffuse maps from these tests. Here is a histogram comparing the pixel values of a max = 50, 100, and 150 wavelength test. The max, sigma, and mean values change.

If I remember right, there was some happiness regarding "let's do it in Kelvin!" or something to that sort. 

![baseline_cut_diffuse](https://cloud.githubusercontent.com/assets/5588290/24522760/6757850a-1545-11e7-93bd-d7b9efa7bc84.png)

**Comment by miguelfmorales** [comment]
I think this is a mostly solved problem. The key is to separate the problem of 'normalization' for point like sources from normalization of a diffuse sky. 

There are two reasons for this. One is that for point or compact sources, since the sky is mostly dark (or dim), even for a ratty PSF one can assume most of the power is from the source. This is not true for diffuse, where the whole sky is full of power. 

The other is that Jy makes sense for a compact source—the total power coming from it. Jy do not make sense for a diffuse source, where one needs to be in either Kelvin or Jy/arcmin^2 or similar brightness units. 

So one can think of our usual normalization as making an image of the sky in Jy/arcmin^2 (or similar), where the beam is complicated. So we look at bright sources and come up with an effective normalization to convert Jy/arcmin^2 to Jy/beam, where the normalization is doing the effective beam integral for us. For point like sources (smaller than a beam), we can then read the brightness in Jy off by saying one beam in Jy/beam is Jy. 

For the diffuse, we really don't want to do a normalization at all. We want to stay in physical brightness units. Of course it is more complicated, because it is diffuse and there is weighting, etc. So a sketch of what I think we should do:

A) Cut our uv-plane so that it is nearly filled. Doesn't have to be perfect, but I'd say high 90's% of uv plane is filled. This means our beams will be well behaved and the sky pixels independent of each other.

B) Uniform weight the uv plane. I'd actually suggest making a pretty strong cut on the weights, so we only include areas of the uv plane that are well measured. Then for everything that is well measured divide the gridded uv plane by the weights to get an accurate measurement for the apparent brightness of the sky in W/m^2 on the ground.

C) Fourier Transform to make an image, and apply corrections to get a low resolution but high fidelity (good PSF) image of the sky in apparent Kelvin. (XX, YY, etc.) No ad-hoc normalization needs to be applied, because we started with a good measurement of W/m^2 in the uv plane, and it was nearly filled. 

D) Correct the brightness by dividing by the beam in image space, to go from apparent brightness to an estimate of the brightness on the sky, and combine the instrumental polarizations to go to I,Q,U,V maps measured in Kelvin (I think Ian has all the machinery to do this step already). 


Caveats:  if uv plane not perfectly filled, we should probably correct flux the the fraction of the uv plane that is zero in going from B to C. Again should be a few percent correction, but we should do it.

**Comment by rlbyrne** [comment]
This should be resolved with PR #185. Just 4 years later!
