### ISSUE TITLE
FHD lowest frequency in vis save files are 1 channel width (80kHz) higher than the lowest frequency in the input uvfits

### ISSUE THREAD

**Issue by bhazelton** [EoRImaging/FHD#50]
The uvfits has the following header values:
CTYPE4  = 'FREQ    '                                                            
CRVAL4  =          1.82435E+08                                                  
CDELT4  =               80000.                                                  
CRPIX4  =                 193.                                                  
my math says this should lead to a minimum frequency (remembering that crpix is 1-indexed) of:
1.82435 x 10^8 - 192 x 80000 = 167075000.0
instead we see a minimum frequency of 167155008.0, which (ignoring the final 8) is 80 kHz higher than it should be

**Comment by isullivan** [comment]
Fixed. It turned out that I had subtracted 1 from the reference frequency in two separate places to account for the FITS convention, which canceled out.
