### ISSUE TITLE
FHD does not take DELAYS, RA & DEC etc from uvfits headers

### ISSUE THREAD

**Issue by wenyang-li** [EoRImaging/FHD#52]
FHD/fhd_core/setupmetadata/fhd_struct_init_meta.pro only reads DELAYS, RA, DEC, RAPHASE, DECPHASE from metafits files. If a metafits file is not provided, FHD does not take those parameters even if they are in uvfits headers.

**Comment by bhazelton** [comment]
I don't believe that Delays are included in MWA uvfits files. The relevant RA/Dec values should be pulled from uvfits. Is this still an issue?

**Comment by wenyang-li** [comment]
It's no longer an issue and I should have closed it. I raised it when I was trying to run simulation on blank uvfits I created, and I did not know uvfits should not have those information.
