### ISSUE TITLE
Upcoming arrays

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#60]
Instrumental parameters need to be updated for new arrays.

1) Phase 2 of the MWA, how will this change the instrumental keyword? Should we just make a new one?

2) HERA cross-correlated with PAPER.  The beams are different between the two, so perhaps we should rope this into a new instrumental keyword...or come up with a new keyword to indicate a cross-correlation between two separate instruments.

**Comment by bhazelton** [comment]
Somewhat related to issue #45

**Comment by bhazelton** [comment]
Need to get cable lengths from MWA metafits files

**Comment by nicholebarry** [comment]
Recent auto-cal commit included MWA PhaseII instrumental parameters. Not much changed, tbh
