### ISSUE TITLE
fill_model_visibilities

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#64]
Should fill_model_visibilities be automatically set for the the instance when the model is made separately from calibration? It is currently hard-coded into the pre-cal model. Also, should that hard-coded instance be made into a keyword_set check and replace?

Don't know the answer of the top of my head. Wanted to ask the question before I forgot.

**Comment by bhazelton** [comment]
The only upside here is reducing computation, which doesn't seem to be very compelling for regular first pass runs. Closing for now.
