### ISSUE TITLE
Size of output calibrations plots

### ISSUE THREAD

**Issue by mkolopanis** [EoRImaging/FHD#69]
the generation of plot_pos in line 42 of plot_cals.pro relies on a hard coded 17 x 9 grid of plots. This restricts the maximum number of plots to 153 per page. Large arrays like HERA in configurations greater than 127 (i.e. hera 217, hera 331, 350) will be unable to utilize the calibration feature of FHD and plotting outputs. 

Can this plot_pos create multiple pages for larger arrays or generate a grid based on the total number of tiles in the array?

**Comment by nicholebarry** [comment]
Multiple pages of plots are made, with a max of 128 antennas/tiles per page. Fixed in cal_cleanup
