### ISSUE TITLE
transfer_calibration does not generate a model

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/FHD#76]
Since calibration is essentially skipped when the transfer_calibration keyword is set, no model is made. While that is certainly a viable option, it's not generally what we want (we generally always subtract a model). 

Do people agree to make a model when transfer_calibration is set?

**Comment by nicholebarry** [comment]
I think it's actually more general the way it is, but the dictionary should be changed to suggest adding model_visibilities during a transferred calibration.

**Comment by isullivan** [comment]
I think the functionality should be left as it is, since it is more general and we risk creating new problems if we try to guess what people want too much. It's good to have it in the dictionary, though, and we could print a warning that calibration visibilities are not being calculated.

**Comment by nicholebarry** [comment]
functionality left as is, fixed in cal_cleanup
