### ISSUE TITLE
Rename obs.beam_integral

### ISSUE THREAD

**Issue by aelanman** [EoRImaging/FHD#91]
The name beam_integral is vague, especially since FHD output is being used in the PAPER pipeline. In FHD, beam_integral currently refers to the total of the absolute square of psf_base_superres, which is Ω_{PP} in the [HERA memo here.](http://reionization.org/wp-content/uploads/2013/03/Power_Spectrum_Normalizations_for_HERA.pdf). I also need the integral of the primary beam itself, which is Ω_P in the memo, but this is not saved with the obs structure.

This issue is to request that beam_integral be renamed primary_beam2_area (ie., primary beam-squared area), and that an additional quantity called primary_beam_area be calculated along with it. The name beam_integral will then be deprecated.

The branch beam2_integral makes this change.

**Comment by isullivan** [comment]
I much prefer beam_power_area over primary_beam2_area. Having two parameters with the same name up to an integer is confusing and suggests that they are alternate calculations of the same quantity.

**Comment by jpober** [comment]
I think beam_power_area is confusing though, as what we mean by the primary beam is sometimes called the power beam (to distinguish it from a single antenna voltage beam).  Is there an issue with primary_beam_sq_area?

**Comment by isullivan** [comment]
primary_beam_sq_area seems fine to me.

**Comment by aelanman** [comment]
Okay. It's renamed in the latest commit.
